{% set name = "kleborate" %}
{% set version = "3.3.0b1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/kleborate-{{ version }}.tar.gz"
  sha256: ff8517f7916c6d5d6dc5d69c760387af92e5e253d283689bfe73cde4fc7bea67

build:
  number: 0
  noarch: python
  entry_points:
    -  kleborate = kleborate.__main__:main
  script:
    - {{ PYTHON }} -m pip install . -vvv --no-deps --no-build-isolation --no-cache-dir
  run_exports:
    - {{ pin_subpackage('kleborate', max_pin='x') }}


requirements:
  host:
    - pip
    - python >=3.11
    - numpy >=1.22
  run:
    - python >=3.11
    - biopython >=1.83
    - numpy >=2.4
    - minimap2
    - mash
    - kaptive
    - ezclermont
    - ectyper
    - stxtyper
    - ncbi-amrfinderplus

test:
  imports:
    - kleborate
  commands:
    - kleborate --help
    - kaptive --help
    - minimap2 --help
    - ectyper --help
    - stxtyper --help
    - amrfinder --help
    - ezclermont --help

about:
  home: "https://kleborate.readthedocs.io/"
  dev_url: "https://github.com/klebgenomics/Kleborate"
  summary: "Kleborate: a tool for typing and screening pathogen genome assemblies"
  license: "GNU General Public License v3 (GPLv3)"
  license_family: GPL3
  license_file: LICENSE
  doc_url: "https://kleborate.readthedocs.io/"


extra:
  recipe-maintainers:
    - Mary Maranga
